global:
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-notifications'

receivers:
  - name: 'slack-notifications'
    slack_configs:
      - channel: '#aleksey_dyakonov'
